/**
 * Swipe encouragement copy in the user's browser UI language (navigator.language).
 * Fallback: English when a locale has no bundle.
 */

export type SwipeEncouragementBundle = {
  left: readonly string[]
  right: readonly string[]
}

/** BCP-47-ish keys: base codes plus zh-Hans / zh-Hant. */
const BUNDLES: Record<string, SwipeEncouragementBundle> = {
  en: {
    left: [
      "Don't give up—you're still learning.",
      'Hard words are normal. Keep going.',
      "Step by step. You've got this.",
      'No rush. Progress takes time.',
      'Skip for now—you can meet it again later.',
      "Stay curious. You're on the path.",
      'Every card counts, even the tough ones.',
      'Consistency beats perfection.',
      'Take a breath. Then next word.',
      'Small wins add up. Keep moving.',
      'Learning curves are real—that is okay.',
      'Your pace is the right pace.',
      'Tough characters today, easier tomorrow.',
      'Breathe. The deck is not judging you.',
      "Missing a word is not failing—it is data.",
      'Come back to it when you are ready.',
      'One more card. You have done harder things.',
      'Frustration means you are stretching. Good.',
      'Nobody masters Chinese in a day. Keep scrolling.',
      'That feeling means you are growing.',
      'Skip, review, repeat—that is the game.',
      'Your brain is still wiring this in.',
      'Lateral moves still move you forward.',
      'Hard left swipes still count as practice.',
      'Rest your eyes if you need to. Then continue.',
      'Comparison is optional. Showing up is not.',
      'The hard ones make the easy ones sweeter.',
      'You are allowed to not know yet.',
      'Stack the reps. Clarity follows.',
      'Next card, fresh start.',
    ],
    right: [
      'Nice one! Keep that energy.',
      "Well done—you're getting sharper.",
      'Great swipe. Chinese is sticking.',
      "You're building real skill. Keep it up!",
      'Strong memory. Celebrate that!',
      'One word closer to fluency.',
      "That's how mastery grows—bit by bit.",
      'Beautiful work. Stay hungry.',
      'Your brain loves these reps. Awesome.',
      "You're leveling up. Keep the rhythm!",
      'Crushed it—that is the spirit.',
      'Yes! That word is in the vault.',
      'Smooth. Trust what you know.',
      'Another brick in the wall—in a good way.',
      'You are reading patterns, not guessing. Nice.',
      'Fluency is made of moments like this.',
      'Keep riding this wave.',
      'Solid recall. Wear it lightly.',
      'That felt clean. More where that came from.',
      'Your shortcuts are working. Keep going.',
      'Celebrate the small—I mean it.',
      'Another win logged. Stack them up.',
      "Radiant swipe. Don't stop now.",
      'You are making this look easy.',
      'That connection just got stronger.',
      'Beautiful rhythm—stay in it.',
      'Proud of you. Onward.',
      "Momentum likes company. You've got it.",
      'Keep feeding the habit. It is paying off.',
      'Shine on—next card awaits.',
    ],
  },
  es: {
    left: [
      'No te rindas—todavía estás aprendiendo.',
      'Las palabras difíciles son normales. Sigue adelante.',
      'Paso a paso. Tú puedes.',
      'Sin prisa. El progreso lleva tiempo.',
      'Saltarla por ahora—más adelante volverás a verla.',
      'Mantén la curiosidad. Vas por buen camino.',
      'Cada tarjeta cuenta, incluso las difíciles.',
      'La constancia vence a la perfección.',
      'Respira hondo. Siguiente palabra.',
      'Las pequeñas victorias suman. Sigue.',
      'Las curvas de aprendizaje son reales—está bien.',
      'Tu ritmo es el ritmo correcto.',
      'Caracteres difíciles hoy, más fáciles mañana.',
      'Respira. El mazo no te juzga.',
      'Olvidar una palabra no es fallar—es información.',
      'Vuelve cuando estés listo.',
      'Una tarjeta más. Ya has hecho cosas más duras.',
      'La frustración significa que te estás estirando. Bien.',
      'Nadie domina el chino en un día. Sigue deslizando.',
      'Esa sensación significa que creces.',
      'Saltar, repasar, repetir—ese es el juego.',
      'Tu cerebro todavía está conectando esto.',
      'Los rodeos también te hacen avanzar.',
      'Los deslizamientos a la izquierda también cuentan como práctica.',
      'Descansa la vista si lo necesitas. Luego sigue.',
      'Compararte es opcional. Aparecer, no.',
      'Las difíciles hacen que las fáciles sepan mejor.',
      'Puedes no saberlo todavía.',
      'Acumula repeticiones. La claridad llegará.',
      'Siguiente tarjeta, nuevo comienzo.',
    ],
    right: [
      '¡Genial! Mantén esa energía.',
      'Bien hecho—cada vez estás más afilado.',
      'Gran desliz. El chino se está quedando.',
      'Estás construyendo habilidad de verdad. ¡Sigue!',
      'Buena memoria. ¡Celébralo!',
      'Una palabra más cerca de la fluidez.',
      'Así crece el dominio—poco a poco.',
      'Hermano trabajo. Sigue con hambre.',
      'A tu cerebro le encantan estas repeticiones. Genial.',
      'Estás subiendo de nivel. Mantén el ritmo.',
      'Lo petaste—ese es el espíritu.',
      '¡Sí! Esa palabra ya está en la caja fuerte.',
      'Fluido. Confía en lo que sabes.',
      'Otro ladrillo en el muro—en el buen sentido.',
      'Estás leyendo patrones, no adivinando. Bien.',
      'La fluidez se hace de momentos como este.',
      'Sigue surfeando esta ola.',
      'Recuerdo sólido. Llévalo con ligereza.',
      'Se sintió limpio. Hay más por venir.',
      'Tus atajos mentales funcionan. Sigue.',
      'Celebra lo pequeño—lo digo en serio.',
      'Otra victoria anotada. Acumúlalas.',
      'Desliz radiante. No pares ahora.',
      'Lo haces parecer fácil.',
      'Esa conexión acaba de fortalecerse.',
      'Qué ritmo tan bonito—mantenlo.',
      'Orgulloso de ti. Adelante.',
      'El impulso busca compañía. Tú lo tienes.',
      'Sigue alimentando el hábito. Está dando frutos.',
      'Brilla—te espera la siguiente tarjeta.',
    ],
  },
  de: {
    left: [
      'Gib nicht auf—du lernst noch.',
      'Schwere Wörter sind normal. Mach weiter.',
      'Schritt für Schritt. Du schaffst das.',
      'Keine Eile. Fortschritt braucht Zeit.',
      'Überspringen für jetzt—du triffst es später wieder.',
      'Bleib neugierig. Du bist auf dem Weg.',
      'Jede Karte zählt, auch die harten.',
      'Ausdauer schlägt Perfektion.',
      'Hol Luft. Nächstes Wort.',
      'Kleine Erfolge addieren sich. Bleib dran.',
      'Lernkurven sind real—das ist okay.',
      'Dein Tempo ist das richtige Tempo.',
      'Schwere Zeichen heute, morgen leichter.',
      'Atme. Das Deck verurteilt dich nicht.',
      'Ein Wort vergessen ist kein Versagen—es sind Daten.',
      'Komm zurück, wenn du bereit bist.',
      'Noch eine Karte. Du hast Schwereres geschafft.',
      'Frustration heißt, du wächst. Gut.',
      'Niemand meistert Chinesisch an einem Tag. Weiter wischen.',
      'Dieses Gefühl heißt, du wächst.',
      'Überspringen, wiederholen, wiederholen—so ist das Spiel.',
      'Dein Gehirn verdrahtet das noch.',
      'Umwege bringen dich trotzdem voran.',
      'Wischen nach links zählt auch als Übung.',
      'Ruhe deine Augen, wenn nötig. Dann weiter.',
      'Vergleichen ist optional. Dabeisein nicht.',
      'Die harten machen die leichten süßer.',
      'Du darfst es noch nicht wissen.',
      'Sammle Wiederholungen. Klarheit folgt.',
      'Nächste Karte, Neustart.',
    ],
    right: [
      'Super! Behalte die Energie.',
      'Gut gemacht—du wirst schärfer.',
      'Starker Swipe. Chinesisch bleibt hängen.',
      'Du baust echtes Können auf. Weiter so!',
      'Starkes Gedächtnis. Feier das!',
      'Ein Wort näher an Flüssigkeit.',
      'So wächst Meisterschaft—Stück für Stück.',
      'Schöne Arbeit. Bleib hungrig.',
      'Dein Gehirn liebt diese Wiederholungen. Klasse.',
      'Du levelst auf. Halte den Rhythmus.',
      'Knackig—genau so.',
      'Ja! Das Wort sitzt.',
      'Smooth. Vertrau dem, was du weißt.',
      'Noch ein Stein im Mauerwerk—im guten Sinn.',
      'Du erkennst Muster statt zu raten. Nice.',
      'Flüssigkeit entsteht aus Momenten wie diesem.',
      'Reit die Welle weiter.',
      'Solides Erinnern. Trag es leicht.',
      'Fühlte sich sauber an. Es gibt mehr.',
      'Deine Abkürzungen funktionieren. Weiter.',
      'Feiere das Kleine—meine ich ernst.',
      'Noch ein Sieg notiert. Stapel sie.',
      'Strahlender Swipe. Hör nicht auf.',
      'Du machst es leicht aussehend.',
      'Die Verbindung wurde gerade stärker.',
      'Schöner Rhythmus—bleib drin.',
      'Stolz auf dich. Vorwärts.',
      'Schwung mag Gesellschaft. Du hast ihn.',
      'Füttere die Gewohnheit weiter. Sie zahlt sich aus.',
      'Strahle—die nächste Karte wartet.',
    ],
  },
  fr: {
    left: [
      "N'abandonne pas—tu apprends encore.",
      'Les mots difficiles sont normaux. Continue.',
      'Pas à pas. Tu y arriveras.',
      'Pas de précipitation. Le progrès prend du temps.',
      "Passe pour l'instant—tu la reverras.",
      'Reste curieux. Tu es sur le bon chemin.',
      'Chaque carte compte, même les dures.',
      'La régularité bat la perfection.',
      'Respire. Mot suivant.',
      "Les petites victoires s'additionnent. Continue.",
      "Les courbes d'apprentissage existent—c'est normal.",
      'Ton rythme est le bon rythme.',
      'Caractères durs aujourd’hui, plus faciles demain.',
      'Respire. Le paquet ne te juge pas.',
      "Oublier un mot n'est pas échouer—ce sont des données.",
      'Reviens quand tu es prêt.',
      'Encore une carte. Tu as fait plus dur.',
      'La frustration signifie que tu progresses. Bien.',
      'Personne ne maîtrise le chinois en un jour. Continue à swiper.',
      'Ce sentiment signifie que tu grandis.',
      'Passer, revoir, répéter—c’est le jeu.',
      'Ton cerveau connecte encore.',
      'Les détours font avancer.',
      'Les swipes à gauche comptent aussi comme pratique.',
      'Repose les yeux si besoin. Puis continue.',
      'Se comparer est optionnel. Être là, non.',
      'Les durs rendent les faciles plus doux.',
      "Tu n'es pas obligé de savoir tout de suite.",
      'Cumule les répétitions. La clarté suivra.',
      'Carte suivante, nouveau départ.',
    ],
    right: [
      'Super ! Garde cette énergie.',
      'Bravo—tu t’aiguis.',
      'Beau swipe. Le chinois accroche.',
      'Tu construis un vrai savoir-faire. Continue !',
      'Bonne mémoire. Fête ça !',
      'Un mot de plus vers la fluidité.',
      'C’est comme ça que la maîtrise grandit—petit à petit.',
      'Beau travail. Reste affamé.',
      'Ton cerveau adore ces répétitions. Génial.',
      'Tu montes de niveau. Garde le rythme.',
      'Écrasé—c’est l’esprit.',
      'Oui ! Ce mot est au coffre.',
      'Fluide. Fais confiance à ce que tu sais.',
      'Une brique de plus—dans le bon sens.',
      'Tu lis des motifs, tu ne devines pas. Bien.',
      'La fluidité se fait de moments comme celui-ci.',
      'Continue sur cette vague.',
      'Bon rappel. Porte-le à la légère.',
      'Ça a fait propre. Il y en a d’autres.',
      'Tes raccourcis fonctionnent. Continue.',
      'Célèbre le petit—je suis sérieux.',
      'Une victoire de plus. Empile-les.',
      'Swipe radieux. Ne t’arrête pas.',
      'Tu rends ça facile.',
      'Ce lien vient de se renforcer.',
      'Beau rythme—reste dedans.',
      'Fier de toi. En avant.',
      'L’élan aime la compagnie. Tu l’as.',
      'Nourris l’habitude. Ça paie.',
      'Brille—la prochaine carte t’attend.',
    ],
  },
  it: {
    left: [
      'Non mollare—stai ancora imparando.',
      'Le parole difficili sono normali. Vai avanti.',
      'Passo dopo passo. Ce la puoi fare.',
      'Nessuna fretta. I progressi richiedono tempo.',
      'Salta per ora—la rivedrai più avanti.',
      'Resta curioso. Sei sulla strada giusta.',
      'Ogni carta conta, anche quelle difficili.',
      'La costanza batte la perfezione.',
      'Respira. Prossima parola.',
      'Le piccole vittorie si sommano. Continua.',
      'Le curve di apprendimento esistono—va bene così.',
      'Il tuo ritmo è quello giusto.',
      'Caratteri difficili oggi, più facili domani.',
      'Respira. Il mazzo non ti giudica.',
      'Dimenticare una parola non è fallire—sono dati.',
      'Torna quando sei pronto.',
      'Un’altra carta. Hai già fatto di peggio.',
      'La frustrazione significa che ti stai spingendo. Bene.',
      'Nessuno impara il cinese in un giorno. Continua a scorrere.',
      'Quella sensazione significa che stai crescendo.',
      'Salta, ripassa, ripeti—è il gioco.',
      'Il tuo cervello sta ancora collegando tutto.',
      'Le deviazioni ti fanno comunque avanzare.',
      'Anche gli swipe a sinistra contano come pratica.',
      'Riposa gli occhi se serve. Poi continua.',
      'Confrontarsi è facoltativo. Esserci, no.',
      'Quelle difficili rendono più dolci le facili.',
      'Puoi ancora non sapere.',
      'Accumula ripetizioni. Arriverà la chiarezza.',
      'Prossima carta, nuovo inizio.',
    ],
    right: [
      'Grande! Mantieni quell’energia.',
      'Ben fatto—stai diventando più acuto.',
      'Ottimo swipe. Il cinese sta attaccando.',
      'Stai costruendo vera abilità. Continua!',
      'Memoria forte. Festeggia!',
      'Una parola più vicino alla fluidità.',
      'Così cresce la padronanza—un po’ alla volta.',
      'Bel lavoro. Resta affamato.',
      'Il tuo cervello adora queste ripetizioni. Fantastico.',
      'Stai salendo di livello. Tieni il ritmo.',
      'Spaccato—questo è lo spirito.',
      'Sì! Quella parola è in cassaforte.',
      'Fluido. Fidati di ciò che sai.',
      'Un altro mattoncino—nel senso buono.',
      'Stai leggendo schemi, non indovinando. Bene.',
      'La fluidità nasce da momenti come questo.',
      'Continua a cavalcare quest’onda.',
      'Richiamo solido. Portalo leggero.',
      'È sembrato pulito. Ce ne sono altri.',
      'Le tue scorciatoie funzionano. Avanti.',
      'Celebra il piccolo—parlo sul serio.',
      'Un’altra vittoria in lista. Impilale.',
      'Swipe radioso. Non fermarti.',
      'Lo rendi facile.',
      'Quella connessione si è appena rafforzata.',
      'Bel ritmo—restaci dentro.',
      'Orgoglioso di te. Avanti.',
      'Lo slancio ama compagnia. Ce l’hai.',
      'Continua a nutrire l’abitudine. Sta pagando.',
      'Brilla—ti aspetta la prossima carta.',
    ],
  },
  pt: {
    left: [
      'Não desista—você ainda está aprendendo.',
      'Palavras difíceis são normais. Continue.',
      'Passo a passo. Você consegue.',
      'Sem pressa. O progresso leva tempo.',
      'Pule por enquanto—vai encontrá-la de novo.',
      'Mantenha a curiosidade. Você está no caminho.',
      'Cada carta conta, até as difíceis.',
      'Constância vence a perfeição.',
      'Respire fundo. Próxima palavra.',
      'Pequenas vitórias somam. Siga.',
      'Curvas de aprendizado são reais—tudo bem.',
      'Seu ritmo é o ritmo certo.',
      'Caracteres difíceis hoje, mais fáceis amanhã.',
      'Respire. O baralho não está te julgando.',
      'Esquecer uma palavra não é falhar—são dados.',
      'Volte quando estiver pronto.',
      'Mais um cartão. Você já fez coisas mais difíceis.',
      'Frustração significa que você está se desafiando. Bom.',
      'Ninguém domina chinês em um dia. Continue deslizando.',
      'Essa sensação significa que você está crescendo.',
      'Pular, revisar, repetir—é o jogo.',
      'Seu cérebro ainda está conectando isso.',
      'Atalhos ainda te levam adiante.',
      'Deslizes para a esquerda também contam como prática.',
      'Descanse os olhos se precisar. Depois continue.',
      'Comparar é opcional. Aparecer, não.',
      'Os difíceis deixam os fáceis mais doces.',
      'Você pode ainda não saber.',
      'Acumule repetições. Clareza vem depois.',
      'Próximo cartão, novo começo.',
    ],
    right: [
      'Muito bem! Mantenha essa energia.',
      'Bom trabalho—você está ficando mais afiado.',
      'Ótimo swipe. O chinês está pegando.',
      'Você está construindo habilidade de verdade. Continue!',
      'Memória forte. Comemore!',
      'Uma palavra mais perto da fluência.',
      'É assim que a maestria cresce—pouco a pouco.',
      'Belo trabalho. Continue com fome.',
      'Seu cérebro adora essas repetições. Incrível.',
      'Você está subindo de nível. Mantenha o ritmo.',
      'Arrasou—esse é o espírito.',
      'Sim! Essa palavra está no cofre.',
      'Fluido. Confie no que você sabe.',
      'Outro tijolo na parede—no bom sentido.',
      'Você está lendo padrões, não chutando. Legal.',
      'Fluência é feita de momentos como este.',
      'Continue surfando essa onda.',
      'Recordação sólida. Leve com leveza.',
      'Foi limpo. Tem mais por vir.',
      'Seus atalhos estão funcionando. Siga.',
      'Celebre o pequeno—falo sério.',
      'Outra vitória anotada. Acumule.',
      'Swipe radiante. Não pare agora.',
      'Você deixa isso fácil.',
      'Essa conexão acabou de ficar mais forte.',
      'Belo ritmo—fique nele.',
      'Orgulhoso de você. Em frente.',
      'Ímpeto gosta de companhia. Você tem.',
      'Alimente o hábito. Está valendo a pena.',
      'Brilhe—o próximo cartão espera.',
    ],
  },
  nl: {
    left: [
      'Geef niet op—je leert nog.',
      'Moeilijke woorden horen erbij. Ga door.',
      'Stap voor stap. Je redt het.',
      'Geen haast. Vooruitgang kost tijd.',
      'Sla nu over—je ziet het later weer.',
      'Blijf nieuwsgierig. Je bent op de goede weg.',
      'Elke kaart telt, ook de moeilijke.',
      'Volharding verslaat perfectie.',
      'Adem in. Volgend woord.',
      'Kleine overwinningen tellen op. Blijf gaan.',
      'Leercurven bestaan—dat is oké.',
      'Jouw tempo is het juiste tempo.',
      'Moeilijke tekens vandaag, morgen makkelijker.',
      'Adem. Het deck oordeelt niet.',
      'Een woord missen is niet falen—het zijn data.',
      'Kom terug wanneer je er klaar voor bent.',
      'Nog een kaart. Je hebt moeilijker gedaan.',
      'Frustratie betekent dat je groeit. Goed.',
      'Niemand beheerst Chinees in één dag. Blijf swipen.',
      'Dat gevoel betekent dat je groeit.',
      'Overslaan, herhalen, herhalen—zo werkt het.',
      'Je brein is nog aan het verbinden.',
      'Omwegen brengen je nog steeds vooruit.',
      'Links swipen telt ook als oefening.',
      'Rust je ogen uit als nodig. Ga dan verder.',
      'Vergelijken is optioneel. Opdagen niet.',
      'De moeilijke maken de makkelijke zoeter.',
      'Je mag het nog niet weten.',
      'Stapel herhalingen. Helderheid volgt.',
      'Volgende kaart, nieuwe start.',
    ],
    right: [
      'Top! Houd die energie vast.',
      'Goed gedaan—je wordt scherper.',
      'Sterke swipe. Chinees blijft hangen.',
      'Je bouwt echt vaardigheid op. Zo door!',
      'Sterk geheugen. Vier het!',
      'Een woord dichter bij vloeiendheid.',
      'Zo groeit meesterschap—beetje bij beetje.',
      'Mooi werk. Blijf hongerig.',
      'Je brein houdt van deze herhalingen. Geweldig.',
      'Je levelt op. Houd het ritme.',
      'Geknald—dat is de spirit.',
      'Ja! Dat woord zit op slot.',
      'Soepel. Vertrouw wat je weet.',
      'Nog een steen in de muur—in goede zin.',
      'Je ziet patronen, je raadt niet. Mooi.',
      'Vloeiendheid ontstaat uit momenten zoals dit.',
      'Blijf deze golf rijden.',
      'Stevige herinnering. Draag het licht.',
      'Voelde schoon. Er komt meer.',
      'Je shortcuts werken. Door.',
      'Vier het kleine—meen ik serieus.',
      'Nog een overwinning. Stapel ze.',
      'Stralende swipe. Stop niet.',
      'Je maakt het makkelijk lijken.',
      'Die verbinding werd net sterker.',
      'Mooi ritme—blijf erin.',
      'Trots op je. Vooruit.',
      'Vaart houdt van gezelschap. Jij hebt het.',
      'Blijf de gewoonte voeden. Het loont.',
      'Straal—de volgende kaart wacht.',
    ],
  },
  pl: {
    left: [
      'Nie poddawaj się—nadal się uczysz.',
      'Trudne słowa są normalne. Idź dalej.',
      'Krok po kroku. Dasz radę.',
      'Bez pośpiechu. Postęp potrzebuje czasu.',
      'Pomiń na razie—wrócisz do tego później.',
      'Bądź ciekawy. Jesteś na dobrej drodze.',
      'Każda karta się liczy, nawet trudne.',
      'Konsekwencja bije perfekcję.',
      'Weź oddech. Następne słowo.',
      'Małe zwycięstwa się sumują. Rób tak dalej.',
      'Krzywe uczenia się są prawdziwe—to w porządku.',
      'Twoje tempo jest właściwe.',
      'Dziś trudne znaki, jutro łatwiej.',
      'Oddychaj. Talia cię nie ocenia.',
      'Zapomnienie słowa to nie porażka—to dane.',
      'Wróć, kiedy będziesz gotów.',
      'Jeszcze jedna karta. Robiłeś trudniejsze rzeczy.',
      'Frustracja znaczy, że się rozciągasz. Dobrze.',
      'Nikt nie opanowuje chińskiego w jeden dzień. Swipuj dalej.',
      'To uczucie znaczy, że rośniesz.',
      'Pomiń, powtórz, powtórz—taka jest gra.',
      'Mózg jeszcze to łączy.',
      'Obejścia też cię posuwają naprzód.',
      'Swipy w lewo też się liczą jako praktyka.',
      'Odpocznij oczom, jeśli trzeba. Potem wracaj.',
      'Porównywanie jest opcjonalne. Bywanie—nie.',
      'Trudne sprawiają, że łatwe smakują lepiej.',
      'Możesz jeszcze nie wiedzieć.',
      'Zbieraj powtórzenia. Jasność przyjdzie.',
      'Następna karta, nowy start.',
    ],
    right: [
      'Świetnie! Utrzymaj tę energię.',
      'Dobra robota—robisz się ostrzejszy.',
      'Mocny swipe. Chiński zostaje.',
      'Budujesz prawdziwą umiejętność. Tak trzymaj!',
      'Silna pamięć. Świętuj to!',
      'Jedno słowo bliżej płynności.',
      'Tak rośnie mistrzostwo—kawałek po kawałku.',
      'Piękna robota. Zostań głodny.',
      'Mózg kocha te powtórzenia. Super.',
      'Awansujesz. Utrzymaj rytm.',
      'Zmiażdżone—o to chodzi.',
      'Tak! To słowo jest w skarbcu.',
      'Płynnie. Ufaj temu, co wiesz.',
      'Kolejna cegła w murze—w dobrym sensie.',
      'Widzisz wzorce, nie zgadujesz. Fajnie.',
      'Płynność składa się z takich chwil.',
      'Jedź tę falę dalej.',
      'Solidne przypomnienie. Noś to lekko.',
      'Było czysto. Jest więcej.',
      'Twoje skróty działają. Dalej.',
      'Świętuj małe—mówię serio.',
      'Kolejne zwycięstwo na liście. Stosuj je.',
      'Promienny swipe. Nie przestawaj.',
      'Sprawiasz, że to wygląda łatwo.',
      'To połączenie właśnie się wzmocniło.',
      'Świetny rytm—zostań w nim.',
      'Dumny z ciebie. Naprzód.',
      'Rozpęd lubi towarzystwo. Masz go.',
      'Karm nawyk. Opłaca się.',
      'Świeć—następna karta czeka.',
    ],
  },
  ru: {
    left: [
      'Не сдавайся—ты всё ещё учишься.',
      'Сложные слова — норма. Продолжай.',
      'Шаг за шагом. У тебя получится.',
      'Без спешки. Прогресс требует времени.',
      'Пропусти пока—встретишь снова позже.',
      'Оставайся любопытным. Ты на пути.',
      'Каждая карта важна, даже сложные.',
      'Упорство важнее идеала.',
      'Сделай вдох. Следующее слово.',
      'Маленькие победы складываются. Двигайся дальше.',
      'Кривые обучения бывают—это нормально.',
      'Твой темп — правильный темп.',
      'Сегодня сложные иероглифы, завтра легче.',
      'Дыши. Колода тебя не осуждает.',
      'Забыть слово — не провал, это данные.',
      'Вернись, когда будешь готов.',
      'Ещё одна карта. Ты делал сложнее.',
      'Раздражение значит, что ты растёшь. Хорошо.',
      'Никто не осваивает китайский за день. Листай дальше.',
      'Это чувство значит, что ты растёшь.',
      'Пропуск, повтор, повтор—такова игра.',
      'Мозг всё ещё связывает это.',
      'Обходы тоже двигают вперёд.',
      'Свайпы влево тоже считаются практикой.',
      'Отдохни глазам, если надо. Потом продолжай.',
      'Сравнение по желанию. Приходить — нет.',
      'Сложное делает лёгкое слаще.',
      'Тебе можно ещё не знать.',
      'Копи повторы. Ясность придёт.',
      'Следующая карта, новый старт.',
    ],
    right: [
      'Отлично! Держи энергию.',
      'Молодец—ты становишься острее.',
      'Сильный свайп. Китайский цепляется.',
      'Ты строишь настоящий навык. Так держать!',
      'Сильная память. Отметь это!',
      'На одно слово ближе к беглости.',
      'Так растёт мастерство—чуть-чуть.',
      'Прекрасная работа. Оставайся голодным.',
      'Мозг любит эти повторы. Класс.',
      'Ты растёшь в уровне. Держи ритм.',
      'Разнесло—вот дух.',
      'Да! Это слово в сейфе.',
      'Плавно. Доверяй тому, что знаешь.',
      'Ещё кирпич в стене—в хорошем смысле.',
      'Ты читаешь закономерности, а не угадываешь. Круто.',
      'Беглость из таких моментов.',
      'Продолжай эту волну.',
      'Крепкое воспоминание. Носи легко.',
      'Было чисто. Впереди ещё.',
      'Твои приёмы работают. Дальше.',
      'Празднуй мелочь—серьёзно.',
      'Ещё победа в списке. Копи их.',
      'Сияющий свайп. Не останавливайся.',
      'Ты делаешь это лёгким.',
      'Связь только что окрепла.',
      'Красивый ритм—держись его.',
      'Горжусь тобой. Вперёд.',
      'Импульс любит компанию. Он у тебя есть.',
      'Подкармливай привычку. Она окупается.',
      'Сияй—следующая карта ждёт.',
    ],
  },
  ja: {
    left: [
      '諦めないで—まだ学んでいます。',
      '難しい単語は普通のこと。続けよう。',
      '一歩ずつ。あなたならできる。',
      '焦らなくていい。上達には時間がかかる。',
      '今はスキップ—あとでまた出会えます。',
      '好奇心を持ち続けて。道は合っています。',
      '難しいカードも、全部カウントされます。',
      '完璧より継続。',
      '深呼吸。次の語へ。',
      '小さな積み重ねが力になる。進もう。',
      '学びには波がある—それでいい。',
      'あなたのペースが正しいペース。',
      '今日は難しい字も、明日は楽に。',
      '呼吸を。デッキはあなたを裁きません。',
      '忘れることは失敗じゃない—データです。',
      '準備ができたら戻ってきて。',
      'あと一枚。もっと難しいことも乗り越えてきた。',
      'イライラは成長のサイン。いい傾向。',
      '中国語を一日で極める人はいない。スワイプを続けて。',
      'その感覚は、成長してる証拠。',
      'スキップ、復習、繰り返し—それがゲーム。',
      '脳はまだつなぎ込み中。',
      '遠回りも前に進む。',
      '左スワイプも練習になる。',
      '目が疲れたら休んで。また続けよう。',
      '比べるのは任意。来ることは必須じゃない。',
      '難しいがあるから、易しいが甘く感じる。',
      'まだ知らなくてもいい。',
      '反復を積もう。明瞭さはあとから来る。',
      '次のカード、新しいスタート。',
    ],
    right: [
      'いいね！その調子。',
      'よくできた—どんどん鋭くなってる。',
      'いいスワイプ。中国語が定着してる。',
      '本当のスキルが育ってる。続けて！',
      '記憶力いいね。祝おう！',
      '流暢さに一歩近づいた。',
      '熟達はこうして少しずつ育つ。',
      '素晴らしい。あくなき欲求を。',
      '脳はこの反復が好き。最高。',
      'レベルアップしてる。リズムを保って。',
      '決まった—その意気だ。',
      'うん！その語は金庫に入った。',
      'スムーズ。知ってることを信じて。',
      '壁のもう一塊—いい意味で。',
      'パターンが読めてる、当ててない。ナイス。',
      '流暢さはこんな瞬間の積み重ね。',
      'この波に乗り続けて。',
      'しっかり思い出せてる。軽くいこう。',
      'キレがあった。まだまだある。',
      'ショートカットが効いてる。進もう。',
      '小さなことも祝って—本気で。',
      'また一勝。積み上げよう。',
      '輝くスワイプ。止まらないで。',
      '簡単に見えてる。',
      'つながりが今、強くなった。',
      'いいリズム—キープ。',
      '誇りに思う。次へ。',
      '勢いは仲間がいい。あなたにはある。',
      '習慣に燃料を。報われてる。',
      '輝いて—次のカードが待ってる。',
    ],
  },
  ko: {
    left: [
      '포기하지 마세요—아직 배우는 중이에요.',
      '어려운 단어는 당연해요. 계속하세요.',
      '한 걸음씩. 할 수 있어요.',
      '서두르지 마세요. 실력은 시간이 걸려요.',
      '지금은 넘어가도—나중에 다시 만나요.',
      '호기심을 유지하세요. 잘 가고 있어요.',
      '어려운 카드도 모두 의미가 있어요.',
      '완벽보다 꾸준함.',
      '숨 쉬고. 다음 단어로.',
      '작은 승리가 쌓여요. 계속 가요.',
      '배움의 곡선은 있어요—괜찮아요.',
      '당신의 속도가 맞는 속도예요.',
      '오늘은 어려운 글자, 내일은 쉬워져요.',
      '숨 쉬어요. 덱이 당신을 판단하지 않아요.',
      '단어를 잊는 건 실패가 아니에요—데이터예요.',
      '준비되면 돌아오세요.',
      '카드 하나 더. 더 힘든 것도 해냈어요.',
      '좌절은 성장 중이라는 뜻이에요. 좋아요.',
      '하루에 중국어를 마스터하는 사람은 없어요. 계속 넘기세요.',
      '그 느낌은 성장하고 있다는 뜻이에요.',
      '넘기기, 복습, 반복—그게 게임이에요.',
      '뇌가 아직 연결 중이에요.',
      '우회해도 앞으로 가요.',
      '왼쪽 스와이프도 연습이에요.',
      '눈이 피로하면 쉬었다가 계속하세요.',
      '비교는 선택이에요. 나오는 건 아니에요.',
      '어려운 게 있어야 쉬운 게 달콤해요.',
      '아직 몰라도 괜찮아요.',
      '반복을 쌓으세요. 명확함은 따라와요.',
      '다음 카드, 새 출발.',
    ],
    right: [
      '멋져요! 그 에너지 유지하세요.',
      '잘했어요—점점 날카로워지고 있어요.',
      '좋은 스와이프. 중국어가 남아요.',
      '진짜 실력을 쌓고 있어요. 계속!',
      '기억력 좋아요. 축하해요!',
      '유창함에 한 단어 더 가까워졌어요.',
      '실력은 이렇게 조금씩 자라요.',
      '아름다운 작업. 배고픔을 유지하세요.',
      '뇌가 이 반복을 좋아해요. 최고예요.',
      '레벨 업 중이에요. 리듬을 유지하세요.',
      '압도적이에요—그 기세예요.',
      '네! 그 단어는 금고에 들어갔어요.',
      '부드러워요. 아는 것을 믿으세요.',
      '벽의 또 한 벽돌—좋은 의미로.',
      '패턴을 읽고 있어요, 추측이 아니에요. 좋아요.',
      '유창함은 이런 순간들로 만들어져요.',
      '이 파도를 계속 타세요.',
      '단단한 기억. 가볍게 가져가요.',
      '깔끔했어요. 더 있어요.',
      '지름길이 먹혀요. 계속하세요.',
      '작은 것도 축하하세요—진심이에요.',
      '또 한 승리. 쌓아가요.',
      '빛나는 스와이프. 멈추지 마세요.',
      '쉬워 보이게 하고 있어요.',
      '그 연결이 방금 강해졌어요.',
      '아름다운 리듬—유지하세요.',
      '자랑스러워요. 앞으로.',
      '기세는 동료가 좋아해요. 당신에게 있어요.',
      '습관에 연료를. 보상받고 있어요.',
      '빛나세요—다음 카드가 기다려요.',
    ],
  },
  th: {
    left: [
      'อย่าถอดใจ—คุณยังเรียนอยู่',
      'คำยากเป็นเรื่องปกติ ไปต่อเลย',
      'ทีละก้าว คุณทำได้',
      'ไม่ต้องรีบ ความก้าวหน้าใช้เวลา',
      'ข้ามไปก่อน—เดี๋ยวเจอกันใหม่',
      'อยากรู้ไว้ คุณอยู่บนเส้นทางที่ถูก',
      'การ์ดทุกใบมีค่า แม้ยาก',
      'สม่ำเสมอชนะความสมบูรณ์แบบ',
      'หายใจลึกๆ คำถัดไป',
      'ชัยชนะเล็กๆ สะสมได้ ไปต่อ',
      'การเรียนรู้มีขึ้นลง—โอเค',
      'จังหวะของคุณคือจังหวะที่ถูก',
      'วันนี้ตัวอักษรยาก พรุ่งนี้ง่ายขึ้น',
      'หายใจ สำรับไม่ตัดสินคุณ',
      'ลืมคำไม่ใช่ความล้มเหลว—เป็นข้อมูล',
      'กลับมาเมื่อพร้อม',
      'อีกหนึ่งการ์ด คุณเคยทำหนักกว่านี้',
      'หงุดหงิดแปลว่าคุณกำลังขยายตัว ดี',
      'ไม่มีใครเก่งจีนในวันเดียว เลื่อนต่อ',
      'ความรู้สึกนั้นแปลว่าคุณกำลังเติบโต',
      'ข้าม ทบทวน ทำซ้ำ—นั่นคือเกม',
      'สมองยังเชื่อมอยู่',
      'อ้อมทางก็ไปข้างหน้าได้',
      'ปัดซ้ายก็นับเป็นฝึก',
      'พักตาถ้าต้องการ แล้วค่อยต่อ',
      'เปรียบเทียบได้เลือก มาไม่บังคับ',
      'ยากทำให้ง่ายหวานขึ้น',
      'ยังไม่รู้ก็ได้',
      'สะสมการทำซ้ำ ความชัดจะตามมา',
      'การ์ดถัดไป เริ่มใหม่',
    ],
    right: [
      'เยี่ยม! คงพลังนั้นไว้',
      'ทำได้ดี—คมขึ้นเรื่อยๆ',
      'สไวป์ดี จีนติดมือ',
      'คุณกำลังสร้างทักษะจริง ไปต่อ!',
      'ความจำแกร่ง ฉลองเลย',
      'อีกหนึ่งคำใกล้ความคล่อง',
      'ความเชี่ยวชาญโตแบบนี้—ทีละนิด',
      'งามมาก อยากเรียนรู้ต่อ',
      'สมองชอบการทำซ้ำนี้ สุดยอด',
      'เลเวลอัปแล้ว จังหวะเดิม',
      'เอาอยู่—นั่นแหละใจ',
      'ใช่! คำนั้นอยู่ในตู้นิรภัย',
      'ลื่นไหล เชื่อในสิ่งที่รู้',
      'อิฐอีกก้อน—ในความหมายดี',
      'คุณอ่านรูปแบบ ไม่ใช่เดา ดี',
      'ความคล่องเกิดจากช่วงเวลาแบบนี้',
      'โต้คลื่นนี้ต่อ',
      'จำแน่น ถือเบาๆ',
      'รู้สึกเนียน ยังมีอีก',
      'ทางลัดใช้ได้ ไปต่อ',
      'ฉลองเรื่องเล็ก—จริงจังนะ',
      'ชนะอีกครั้ง สะสมไว้',
      'สไวป์เปล่งประกาย อย่าหยุด',
      'คุณทำให้ดูง่าย',
      'ความเชื่อมแข็งแรงขึ้นเพิ่งนี้',
      'จังหวะสวย—อยู่ในนั้น',
      'ภูมิใจในตัวคุณ ไปข้างหน้า',
      'โมเมนตัมชอบเพื่อน คุณมี',
      'หล่อเลี้ยงนิสัย คุ้มค่า',
      'เปล่งแสง—การ์ดถัดไปรอ',
    ],
  },
  'zh-Hans': {
    left: [
      '别放弃——你还在学习。',
      '难词很正常，继续就好。',
      '一步一步来，你可以的。',
      '别急，进步需要时间。',
      '先跳过——以后还会遇到。',
      '保持好奇，你在路上。',
      '每张都算数，难的也算。',
      '坚持胜过完美。',
      '深呼吸，下一个词。',
      '小胜利会累积，继续。',
      '学习有起伏——没关系。',
      '你的节奏就是对的节奏。',
      '今天难的字，明天会更轻松。',
      '呼吸，卡组不会评判你。',
      '忘了不是失败——是数据。',
      '准备好了再回来。',
      '再来一张，你做过更难的事。',
      '烦躁说明你在拉伸，很好。',
      '没人一天精通中文，继续滑。',
      '那种感觉说明你在成长。',
      '跳过、复习、重复——这就是玩法。',
      '大脑还在连接这些。',
      '绕路也在前进。',
      '左滑也算练习。',
      '眼睛累了就休息，再继续。',
      '比较可有可无，出现不必。',
      '难的让简单的更甜。',
      '允许自己还不知道。',
      '堆重复，清晰会跟上。',
      '下一张，新开始。',
    ],
    right: [
      '太棒了！保持这股劲。',
      '做得好——你越来越敏锐。',
      '滑得漂亮，中文在扎根。',
      '你在积累真本事，继续！',
      '记忆力强，庆祝一下！',
      '离流利又近一个词。',
      '精通就是这样一点点长出来。',
      '漂亮，保持饥饿感。',
      '大脑爱这些重复，厉害。',
      '你在升级，保持节奏。',
      '碾压——就是这个劲头。',
      '对！那个词进保险库了。',
      '顺滑，相信你知道的。',
      '墙上又一块砖——好话。',
      '你在读规律，不是瞎猜，好。',
      '流利由这样的瞬间堆成。',
      '继续乘这波。',
      '记得牢，轻松带着走。',
      '很干净，后面还有。',
      '你的捷径管用，继续。',
      '庆祝小事——我是认真的。',
      '又记一笔胜利，堆起来。',
      '闪亮的滑动，别停。',
      '你让它看起来很容易。',
      '连接刚刚更强了。',
      '节奏很美——保持住。',
      '为你骄傲，向前。',
      '势头喜欢同伴，你有。',
      '喂养习惯，它在回报。',
      '闪耀——下一张在等你。',
    ],
  },
  'zh-Hant': {
    left: [
      '別放棄——你還在學習。',
      '難字很正常，繼續就好。',
      '一步一步來，你可以的。',
      '別急，進步需要時間。',
      '先跳過——以後還會遇到。',
      '保持好奇，你在路上。',
      '每張都算數，難的也算。',
      '堅持勝過完美。',
      '深呼吸，下一個字。',
      '小勝利會累積，繼續。',
      '學習有起伏——沒關係。',
      '你的節奏就是對的節奏。',
      '今天難的字，明天會更輕鬆。',
      '呼吸，卡組不會評判你。',
      '忘了不是失敗——是資料。',
      '準備好了再回來。',
      '再來一張，你做過更難的事。',
      '煩躁說明你在拉伸，很好。',
      '沒人一天精通中文，繼續滑。',
      '那種感覺說明你在成長。',
      '跳過、複習、重複——這就是玩法。',
      '大腦還在連接這些。',
      '繞路也在前進。',
      '左滑也算練習。',
      '眼睛累了就休息，再繼續。',
      '比較可有可無，出現不必。',
      '難的讓簡單的更甜。',
      '允許自己還不知道。',
      '堆重複，清晰會跟上。',
      '下一張，新開始。',
    ],
    right: [
      '太棒了！保持這股勁。',
      '做得好——你越來越敏銳。',
      '滑得漂亮，中文在扎根。',
      '你在累積真本事，繼續！',
      '記憶力強，慶祝一下！',
      '離流利又近一個字。',
      '精通就是這樣一點點長出來。',
      '漂亮，保持飢餓感。',
      '大腦愛這些重複，厲害。',
      '你在升級，保持節奏。',
      '碾壓——就是這個勁頭。',
      '對！那個字進保險庫了。',
      '順滑，相信你知道的。',
      '牆上又一塊磚——好話。',
      '你在讀規律，不是瞎猜，好。',
      '流利由這樣的瞬間堆成。',
      '繼續乘這波。',
      '記得牢，輕鬆帶著走。',
      '很乾淨，後面還有。',
      '你的捷徑管用，繼續。',
      '慶祝小事——我是認真的。',
      '又記一筆勝利，堆起來。',
      '閃亮的滑動，別停。',
      '你讓它看起來很容易。',
      '連結剛剛更強了。',
      '節奏很美——保持住。',
      '為你驕傲，向前。',
      '勢頭喜歡同伴，你有。',
      '餵養習慣，它在回報。',
      '閃耀——下一張在等你。',
    ],
  },
  nb: {
    left: [
      'Ikke gi opp—du lærer fortsatt.',
      'Vanskelige ord er normale. Fortsett.',
      'Steg for steg. Du klarer det.',
      'Ingen hast. Fremgang tar tid.',
      'Hopp over nå—du møter det igjen senere.',
      'Hold nysgjerrigheten. Du er på vei.',
      'Hvert kort teller, også de vanskelige.',
      'Konsekvens slår perfeksjon.',
      'Pust inn. Neste ord.',
      'Små seire summer seg. Hold på.',
      'Læringskurver finnes—det er greit.',
      'Ditt tempo er riktig tempo.',
      'Vanskelige tegn i dag, lettere i morgen.',
      'Pust. Kortstokken dømmer deg ikke.',
      'Å glemme et ord er ikke å feile—det er data.',
      'Kom tilbake når du er klar.',
      'Ett kort til. Du har gjort verre.',
      'Frustrasjon betyr at du strekker deg. Bra.',
      'Ingen mestrer kinesisk på én dag. Sveip videre.',
      'Den følelsen betyr at du vokser.',
      'Hopp over, repeter, repeter—det er spillet.',
      'Hjernen kobler fortsatt dette.',
      'Omveier flytter deg likevel fremover.',
      'Venstresveip teller også som trening.',
      'Hvil øynene om nødvendig. Fortsett så.',
      'Sammenligning er valgfritt. Å møte opp, ikke.',
      'De vanskelige gjør de lette søtere.',
      'Du får lov til å ikke vite ennå.',
      'Stakk repetisjoner. Klarhet følger.',
      'Neste kort, ny start.',
    ],
    right: [
      'Knallbra! Hold energien.',
      'Bra jobbet—du blir skarpere.',
      'Sterk sveip. Kinesisk sitter.',
      'Du bygger ekte ferdighet. Fortsett!',
      'Sterkt minne. Feir det!',
      'Ett ord nærmere flyt.',
      'Slik vokser mestering—bit for bit.',
      'Vakkert arbeid. Hold sulten.',
      'Hjernen elsker disse repetisjonene. Rått.',
      'Du leveler opp. Hold rytmen.',
      'Knust—det er ånden.',
      'Ja! Ordet er i safe.',
      'Flytende. Stol på det du vet.',
      'Nok en murstein—i god forstand.',
      'Du leser mønstre, ikke gjetter. Fint.',
      'Flyt bygges av øyeblikk som dette.',
      'Surf denne bølgen videre.',
      'Solid hukommelse. Bær det lett.',
      'Føltes rent. Mer kommer.',
      'Snarveiene dine fungerer. Videre.',
      'Feir det små—jeg mener det.',
      'Nok en seier. Stabel dem.',
      'Strålende sveip. Ikke stopp.',
      'Du får det til å se lett ut.',
      'Koblingen ble nettopp sterkere.',
      'Fin rytme—hold deg i den.',
      'Stolt av deg. Fremover.',
      'Momentum liker selskap. Du har det.',
      'Fôr vanen. Den lønner seg.',
      'Skinn—neste kort venter.',
    ],
  },
}

/**
 * Maps navigator.language to a bundle key. Unknown bases still returned;
 * getSwipeEncouragementBundle falls back to English.
 */
export function resolveSwipeEncouragementLang(): string {
  if (typeof navigator === 'undefined') return 'en'
  const full = (navigator.language || 'en').toLowerCase().replace(/_/g, '-')
  if (full.startsWith('zh')) {
    if (
      full.includes('hant') ||
      full.includes('tw') ||
      full.includes('hk') ||
      full.includes('mo') ||
      full === 'zh-tw' ||
      full === 'zh-hk'
    ) {
      return 'zh-Hant'
    }
    return 'zh-Hans'
  }
  const base = full.split('-')[0] || 'en'
  if (base === 'no' || base === 'nb') return 'nb'
  return base
}

export function getSwipeEncouragementBundle(langKey: string): SwipeEncouragementBundle {
  return BUNDLES[langKey] ?? BUNDLES.en
}
